server:
    port: 8001

spring:
    profiles:
        active: test
    redis:
        host: localhost
        port: 6379
        db: 8
        password:    #密码 (默认为空)

mybatis-plus:
  configuration:
    #在控制台打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  global-config:
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: 0
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 1
      # 默认数据库表下划线命名
      table-underline: true

